/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.InspectionManager;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.InspectionWorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Youming Zheng
 */
public class Analysis extends javax.swing.JPanel {

    /**
     * Creates new form Analysis
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    Organization organization;
    Enterprise enterprise;
    Network network;
    EcoSystem system;
    ArrayList<InspectionWorkRequest> list=new ArrayList<InspectionWorkRequest>();

    Analysis(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userAccount=userAccount;
        this.organization=organization;
        this.enterprise=enterprise;
        this.network=network;
        this.system=system;
    }
    
    public void populateTable(ArrayList<InspectionWorkRequest> list){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        model.setRowCount(0);
        
        for (InspectionWorkRequest iwr : list){
            Object[] row = new Object[7];
            row[0] =iwr;
            row[1] = iwr.getCustomer().getAddress();
            row[2] = iwr.getCustomer().getId();
            row[3] = iwr.getFirstInspection();
            row[4] = (iwr.getSecondInspection() == null ? "waiting" : iwr.getSecondInspection());
            row[5] = (iwr.getThirdInspection() == null ? "waiting" : iwr.getThirdInspection());
            row[6] = iwr.getStatus();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFirst = new javax.swing.JTextField();
        txtSecond = new javax.swing.JTextField();
        txtThird = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtBreed = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtSpecies = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtAID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField13 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Adopter Name", "Address", "ID", "First Inspection", "Second", "Third", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 92, 736, 258));

        jButton1.setText("See Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 368, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("All Completed Requests");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 58, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Three C");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 58, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Two C");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 58, -1, -1));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Three A");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 58, -1, -1));

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("Expired Requests");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 58, -1, -1));

        jLabel8.setText("Address:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 568, -1, -1));

        txtAddress.setEditable(false);
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 565, 188, -1));

        txtEmail.setEditable(false);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 605, 188, -1));

        txtName.setEditable(false);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 485, 188, -1));

        txtID.setEditable(false);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 525, 188, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("Customer:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 438, -1, -1));

        jLabel5.setText("Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 488, -1, -1));

        jLabel6.setText("ID:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 528, -1, -1));

        jLabel7.setText("Email:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 608, -1, -1));

        jLabel1.setText("First Inspection:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 488, -1, -1));

        jLabel3.setText("Third Inspection:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 568, -1, -1));

        jLabel4.setText("Second Inspection:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 528, -1, -1));

        txtFirst.setEditable(false);
        txtFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstActionPerformed(evt);
            }
        });
        add(txtFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 485, 51, -1));

        txtSecond.setEditable(false);
        txtSecond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSecondActionPerformed(evt);
            }
        });
        add(txtSecond, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 525, 51, -1));

        txtThird.setEditable(false);
        txtThird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThirdActionPerformed(evt);
            }
        });
        add(txtThird, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 565, 51, -1));

        jLabel16.setText("ID:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 528, -1, -1));

        jLabel13.setText("Color:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 608, -1, -1));

        jLabel14.setText("Breed:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 568, -1, -1));

        txtBreed.setEditable(false);
        txtBreed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBreedActionPerformed(evt);
            }
        });
        add(txtBreed, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 565, 188, -1));

        txtColor.setEditable(false);
        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });
        add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 605, 188, -1));

        txtSpecies.setEditable(false);
        txtSpecies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpeciesActionPerformed(evt);
            }
        });
        add(txtSpecies, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 485, 188, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel9.setText("Animal:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 438, -1, -1));

        txtAID.setEditable(false);
        txtAID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAIDActionPerformed(evt);
            }
        });
        add(txtAID, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 525, 188, -1));

        jLabel15.setText("Species:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 488, -1, -1));
        add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 369, 330, -1));

        jButton2.setText("Send Message to All");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 368, -1, -1));

        jButton3.setText("Send Message to the Adopter");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 654, -1, -1));
        add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 655, 330, -1));

        jButton4.setText("Cast to Expired");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 368, -1, -1));

        jButton5.setText("Renew");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 400, -1, -1));

        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 400, -1, -1));

        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 686, -1, -1));

        jButton8.setText("Pie Chart");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 400, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel10.setText("Inspection Analysis");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstActionPerformed

    private void txtSecondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSecondActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSecondActionPerformed

    private void txtThirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThirdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThirdActionPerformed

    private void txtBreedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBreedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBreedActionPerformed

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    private void txtSpeciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpeciesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpeciesActionPerformed

    private void txtAIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAIDActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        list.clear();
        jButton4.setEnabled(true);
        
        if(jRadioButton1.isSelected()){
            for(InspectionWorkRequest iwr:organization.getInspectionWorkQueue().getWorkRequestList()){
                if(iwr.getStatus().equalsIgnoreCase("Completed")){
                    list.add(iwr);
                }
            }
        }
        
        populateTable(list);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        jButton4.setEnabled(true);
        list.clear();
        
        if(jRadioButton2.isSelected()){
            for(InspectionWorkRequest iwr:organization.getInspectionWorkQueue().getWorkRequestList()){
                    if(iwr.getThirdInspection()!= null){
                        if(iwr.getFirstInspection().equals("C")
                           && iwr.getSecondInspection().equals("C")
                           && iwr.getThirdInspection().equals("C")){
                            list.add(iwr);
                        }
                    }
            }
        }
        
        populateTable(list);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        list.clear();
        jButton4.setEnabled(true);
        
        if(jRadioButton3.isSelected()){
            for(InspectionWorkRequest iwr:organization.getInspectionWorkQueue().getWorkRequestList()){
                int i=0;
                
                
                if(iwr.getSecondInspection()!= null){
                    if(iwr.getFirstInspection().equals("C")){
                        i++;
                    }
                    if(iwr.getSecondInspection().equals("C")){
                        i++;
                    }
                }
                    if(iwr.getThirdInspection() != null  ){
                        if(iwr.getThirdInspection().equals("C")){
                            i++;
                        }
                        
                    }
                
                
        
                if(i==2){
                    list.add(iwr);
                }
            }
        }
        
        populateTable(list);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        list.clear();
        jButton4.setEnabled(true);
        
        if(jRadioButton4.isSelected()){
            for(InspectionWorkRequest iwr:organization.getInspectionWorkQueue().getWorkRequestList()){
                int i=0;
                
                if(iwr.getThirdInspection() != null){
                    if(iwr.getFirstInspection().equals("A")){
                    i++;
                }
                if(iwr.getSecondInspection().equals("A")){
                    i++;
                }
                if(iwr.getThirdInspection().equals("A")){
                    i++;
                }
                }
                
                
                if(i==3){
                    list.add(iwr);
                }
            }
        }
        
        populateTable(list);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        list.clear();
        jButton4.setEnabled(false);
        
        if(jRadioButton5.isSelected()){
            for(InspectionWorkRequest iwr:organization.getInspectionWorkQueue().getWorkRequestList()){
                if(iwr.getStatus().equals("Expired")){
                    list.add(iwr);
                }
            }
        }
        
        populateTable(list);
        
        
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row first!","Warining",JOptionPane.WARNING_MESSAGE);
            return;
        }
        InspectionWorkRequest iwr=(InspectionWorkRequest)jTable1.getValueAt(selectedRow, 0);
        
        txtName.setText(iwr.getCustomer().getName());
        txtID.setText(String.valueOf(iwr.getCustomer().getId()));
        txtAddress.setText(iwr.getCustomer().getAddress());
        txtEmail.setText(iwr.getCustomer().getEmail());
        
        txtFirst.setText(iwr.getFirstInspection());
        txtSecond.setText(iwr.getSecondInspection());
        txtThird.setText(iwr.getThirdInspection());
        
        txtSpecies.setText(iwr.getAnimal().getSpecies());
        txtAID.setText(String.valueOf(iwr.getAnimal().getID()));
        txtBreed.setText(iwr.getAnimal().getBreed());
        txtColor.setText(iwr.getAnimal().getColor());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row first!","Warining",JOptionPane.WARNING_MESSAGE);
            return;
        }
        InspectionWorkRequest iwr=(InspectionWorkRequest)jTable1.getValueAt(selectedRow, 0);
        
        if(iwr.getThirdInspection()==null){
            JOptionPane.showMessageDialog(null, "The customer has not go through all three Inspection visit!","Warining",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(iwr.getFirstInspection().equals("C")
           && iwr.getSecondInspection().equals("C")
           && iwr.getThirdInspection().equals("C")){
            JOptionPane.showMessageDialog(null, "The customer is not qualified to pass the Inspection due to low inspection result","Warining",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        iwr.setStatus("Expired");
        list.remove(iwr);
        populateTable(list);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row first!","Warining",JOptionPane.WARNING_MESSAGE);
            return;
        }
        InspectionWorkRequest iwr=(InspectionWorkRequest)jTable1.getValueAt(selectedRow, 0);
        
        iwr.setFirstInspection(null);
        iwr.setSecondInspection(null);
        iwr.setThirdInspection(null);
        iwr.setVolunteer(null);
        iwr.setStatus("Generated");
        JOptionPane.showMessageDialog(null, "Customer is assigned to a new round of inspection now","Warining",JOptionPane.WARNING_MESSAGE);
        
        list.remove(iwr);
        populateTable(list);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row first!","Warining",JOptionPane.WARNING_MESSAGE);
            return;
        }
        InspectionWorkRequest iwr=(InspectionWorkRequest)jTable1.getValueAt(selectedRow, 0);
        
        int dialogButton=JOptionPane.YES_NO_OPTION;
            int dialogResult=JOptionPane.showConfirmDialog(null, "Are you sure to delete all the record of this adoption?", "Waring",dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
                organization.getInspectionWorkQueue().getWorkRequestList().remove(iwr);
                list.remove(iwr);
                populateTable(list);
            }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         int threeC = 0;
        int twoC = 0;
        int threeA = 0;
        
        for(InspectionWorkRequest iwr:organization.getInspectionWorkQueue().getWorkRequestList()){
                if(iwr.getThirdInspection()!= null){
                    if(iwr.getFirstInspection().equals("C")
                       && iwr.getSecondInspection().equals("C")
                       && iwr.getThirdInspection().equals("C")){
                        threeC++;
                    }
                }
        }


        for(InspectionWorkRequest iwr:organization.getInspectionWorkQueue().getWorkRequestList()){
            int i=0;

             if(iwr.getSecondInspection()!= null){
                    if(iwr.getFirstInspection().equals("C")){
                        i++;
                    }
                    if(iwr.getSecondInspection().equals("C")){
                        i++;
                    }
                }
                    if(iwr.getThirdInspection() != null  ){
                        if(iwr.getThirdInspection().equals("C")){
                            i++;
                        }
                        
                    }


            if(i==2){
                twoC++;
            }
        }
        
        for(InspectionWorkRequest iwr:organization.getInspectionWorkQueue().getWorkRequestList()){
                int i=0;
                 if(iwr.getThirdInspection() != null){
                    if(iwr.getFirstInspection().equals("A")){
                    i++;
                }
                if(iwr.getSecondInspection().equals("A")){
                    i++;
                }
                if(iwr.getThirdInspection().equals("A")){
                    i++;
                }
                }
                
                if(i==3){
                    threeA++;
                }
            }
            
        DefaultPieDataset pieDataset = new DefaultPieDataset();
        pieDataset.setValue("Three C", threeC);
        pieDataset.setValue("Two C", twoC);
        pieDataset.setValue("Three A", threeA);
        JFreeChart chart = ChartFactory.createPieChart("Pie Chart", pieDataset, true, true, true);
        PiePlot p = (PiePlot)chart.getPlot();
        //p.setForegroundAlpha(TOP_ALIGNMENT);
        ChartFrame frame = new ChartFrame("Pie Chart",chart);
        frame.setVisible(true);
        frame.setSize(450,500);
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField txtAID;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBreed;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirst;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSecond;
    private javax.swing.JTextField txtSpecies;
    private javax.swing.JTextField txtThird;
    // End of variables declaration//GEN-END:variables
}
