/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.InspectionManager;

import Business.EcoSystem;
import Business.Enterprise.CustomerAndVolunteerEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.InspectionWorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Youming Zheng
 */
public class SelectInspectionWorkRequest extends javax.swing.JPanel {

    /**
     * Creates new form SendInspectionWorkRequest
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    Organization organization;
    Enterprise enterprise;
    Network network;
    EcoSystem system;
    ArrayList<InspectionWorkRequest> upperList=new ArrayList<InspectionWorkRequest>();
    ArrayList<InspectionWorkRequest> lowerList=new ArrayList<InspectionWorkRequest>();
    SimpleDateFormat df=new SimpleDateFormat("yyyy-MM-dd");

    SelectInspectionWorkRequest(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userAccount=userAccount;
        this.organization=organization;
        this.enterprise=enterprise;
        this.network=network;
        this.system=system;
        
        populateComboBox();
    }
    
    public void populateComboBox(){
        jComboBox1.removeAllItems();
        
        double a=5;
        double b=10;
        double c=15;
        double d=25;
        jComboBox1.addItem(a);
        jComboBox1.addItem(b);
        jComboBox1.addItem(c);
        jComboBox1.addItem(d);

    }
    
    public void populateUpperTable(ArrayList<InspectionWorkRequest> list){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        model.setRowCount(0);
        
        for (InspectionWorkRequest iwr : list){
            Object[] row = new Object[6];
            row[0] =iwr;
            row[1] = iwr.getCustomer().getAddress();
            row[2] = iwr.getAnimal().getSpecies();
            row[3] = iwr.getAnimal().getBreed();
            row[4] = iwr.getAnimal().getColor();
            if(!iwr.getStatus().equals("Generated")){
                row[5] =df.format(iwr.getLastTimeCheckDate()) ;
            }else
                row[5] = "Just Generated";
            model.addRow(row);
        }
    }
    
    
    public void populateLowerTable(ArrayList<InspectionWorkRequest> list){
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        
        model.setRowCount(0);
        
        for (InspectionWorkRequest iwr : list){
            Object[] row = new Object[6];
            row[0] =iwr;
            row[1] = iwr.getCustomer().getAddress();
            row[2] = iwr.getAnimal().getID();
            row[3] = iwr.getVolunteer()==null ? "Unassigned" : iwr.getVolunteer().getName();
            row[4] = df.format(new Date(iwr.getLastTimeCheckDate().getTime()+(long)30*24*60*60*1000));
            row[5] = iwr.getStatus();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtVAddress = new javax.swing.JTextField();
        txtVEmail = new javax.swing.JTextField();
        txtVName = new javax.swing.JTextField();
        txtVID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtBreed = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtSpecies = new javax.swing.JTextField();
        txtAID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Adopter Name", "Address", "Animal Species", "Breed", "Color", "Last Check Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 83, 906, 199));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 52, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("days from next Inspection");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 52, -1, -1));

        jButton1.setText("Send single Request to Volunteers");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 289, -1, -1));

        jButton2.setText("Send all on the list to Volunteers");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 289, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Adopter Name", "Address", "Animal ID", "Volunteer Name", "Supposed Check Time", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 397, 906, 215));

        jButton3.setText("Check out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 365, -1, -1));

        jButton4.setText("See Details");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(821, 619, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("Customer:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 657, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setText("Volunteer:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 657, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setText("Animal:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 657, -1, -1));

        jLabel5.setText("Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 707, -1, -1));

        jLabel6.setText("ID:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 747, -1, -1));

        jLabel7.setText("Email:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 827, -1, -1));

        jLabel8.setText("Address:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 787, -1, -1));

        txtAddress.setEditable(false);
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 784, 188, -1));

        txtEmail.setEditable(false);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 824, 188, -1));

        txtName.setEditable(false);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 704, 188, -1));

        txtID.setEditable(false);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 744, 188, -1));

        jLabel9.setText("Email:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 827, -1, -1));

        jLabel10.setText("Address:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 787, -1, -1));

        txtVAddress.setEditable(false);
        txtVAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVAddressActionPerformed(evt);
            }
        });
        add(txtVAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 784, 188, -1));

        txtVEmail.setEditable(false);
        txtVEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVEmailActionPerformed(evt);
            }
        });
        add(txtVEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 824, 188, -1));

        txtVName.setEditable(false);
        txtVName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVNameActionPerformed(evt);
            }
        });
        add(txtVName, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 704, 188, -1));

        txtVID.setEditable(false);
        txtVID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVIDActionPerformed(evt);
            }
        });
        add(txtVID, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 744, 188, -1));

        jLabel11.setText("Name:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 707, -1, -1));

        jLabel12.setText("ID:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 747, -1, -1));

        jLabel13.setText("Color:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 827, -1, -1));

        jLabel14.setText("Breed:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 787, -1, -1));

        txtBreed.setEditable(false);
        txtBreed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBreedActionPerformed(evt);
            }
        });
        add(txtBreed, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 784, 188, -1));

        txtColor.setEditable(false);
        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });
        add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 824, 188, -1));

        txtSpecies.setEditable(false);
        txtSpecies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpeciesActionPerformed(evt);
            }
        });
        add(txtSpecies, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 704, 188, -1));

        txtAID.setEditable(false);
        txtAID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAIDActionPerformed(evt);
            }
        });
        add(txtAID, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 744, 188, -1));

        jLabel15.setText("Species:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 707, -1, -1));

        jLabel16.setText("ID:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 747, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("All Requests Sent");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 365, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Requests Assigned");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 365, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Requests Unassigned");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 365, -1, -1));

        jButton6.setText("Check out");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 51, -1, -1));

        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 853, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel17.setText("Inspection Work Request");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtVAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVAddressActionPerformed

    private void txtVEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVEmailActionPerformed

    private void txtVNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVNameActionPerformed

    private void txtVIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVIDActionPerformed

    private void txtBreedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBreedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBreedActionPerformed

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    private void txtSpeciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpeciesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpeciesActionPerformed

    private void txtAIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAIDActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row first!","Warining",JOptionPane.WARNING_MESSAGE);
            return;
        }
        InspectionWorkRequest iwr=(InspectionWorkRequest)jTable1.getValueAt(selectedRow, 0);
        
        for(Enterprise en:network.getEnterpriseDirectory().getEnterpriseList()){
            if(en instanceof CustomerAndVolunteerEnterprise){
                en.getInspectionWorkQueue().getWorkRequestList().add(iwr);
                iwr.setStatus("Sent");
                iwr.setSender(userAccount);
                break;
            }
        }
        
        upperList.remove(iwr);
        populateUpperTable(upperList);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        for(Enterprise en:network.getEnterpriseDirectory().getEnterpriseList()){
            if(en instanceof CustomerAndVolunteerEnterprise){
                for(InspectionWorkRequest iwr:upperList){
                    en.getInspectionWorkQueue().getWorkRequestList().add(iwr);
                    iwr.setStatus("Sent");
                    iwr.setSender(userAccount);
                }
            }
        }
        
        upperList.clear();
        populateUpperTable(upperList);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        populateLowerTable(lowerList);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable2.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row first!","Warining",JOptionPane.WARNING_MESSAGE);
            return;
        }
        InspectionWorkRequest iwr=(InspectionWorkRequest)jTable2.getValueAt(selectedRow, 0);
        
        txtName.setText(iwr.getCustomer().getName());
        txtID.setText(String.valueOf(iwr.getCustomer().getId()));
        txtAddress.setText(iwr.getCustomer().getAddress());
        txtEmail.setText(iwr.getCustomer().getEmail());
        
        if(iwr.getStatus().equals("Assigned")){
            txtVName.setText(iwr.getVolunteer().getName());
            txtVID.setText(String.valueOf(iwr.getVolunteer().getId()));
            txtVAddress.setText(iwr.getVolunteer().getAddress());
            txtVEmail.setText(iwr.getVolunteer().getEmail());
        }else if(iwr.getStatus().equals("Sent")){
            txtVName.setText("Volunteer Unassigned");
            txtVID.setText("Volunteer Unassigned");
            txtVAddress.setText("Volunteer Unassigned");
            txtVEmail.setText("Volunteer Unassigned");
        }
        
        
        txtSpecies.setText(iwr.getAnimal().getSpecies());
        txtAID.setText(String.valueOf(iwr.getAnimal().getID()));
        txtBreed.setText(iwr.getAnimal().getBreed());
        txtColor.setText(iwr.getAnimal().getColor());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        lowerList.clear();
        
        if(jRadioButton1.isSelected()){
            for(InspectionWorkRequest iwr:organization.getInspectionWorkQueue().getWorkRequestList()){
                if(iwr.getStatus().equalsIgnoreCase("Sent") || iwr.getStatus().equalsIgnoreCase("Assigned")){
                    lowerList.add(iwr);
                }
            }
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        lowerList.clear();
        
        if(jRadioButton2.isSelected()){
            for(InspectionWorkRequest iwr:organization.getInspectionWorkQueue().getWorkRequestList()){
                if(iwr.getStatus().equalsIgnoreCase("Assigned")){
                    lowerList.add(iwr);
                }
            }
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        lowerList.clear();
        
        if(jRadioButton3.isSelected()){
            for(InspectionWorkRequest iwr:organization.getInspectionWorkQueue().getWorkRequestList()){
                if(iwr.getStatus().equalsIgnoreCase("Sent")){
                    lowerList.add(iwr);
                }
            }
        }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        upperList.clear();
  
        double i=(Double)jComboBox1.getSelectedItem();
        for(InspectionWorkRequest iwr:organization.getInspectionWorkQueue().getWorkRequestList()){
            if(iwr.getStatus().equalsIgnoreCase("Generated") || iwr.getStatus().equalsIgnoreCase("Completed")){
                if(iwr.nextTimeCheck(i)){
                    upperList.add(iwr);
                }
            }
        }
        
        populateUpperTable(upperList);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtAID;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBreed;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSpecies;
    private javax.swing.JTextField txtVAddress;
    private javax.swing.JTextField txtVEmail;
    private javax.swing.JTextField txtVID;
    private javax.swing.JTextField txtVName;
    // End of variables declaration//GEN-END:variables
}
