/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CertificationManager;

import Business.Animal.Animal;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.InspectionOrganization;
import Business.Organization.InventoryOrganization;
import Business.Organization.Organization;
import Business.Person.Customer;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AdoptionWorkRequest;
import Business.WorkQueue.InspectionWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emmet Zhao
 */
public class ReciveAdoptionWorkRequest extends javax.swing.JPanel {

    /**
     * Creates new form ReciveApplicationWorkRequest
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    Organization organization;
    Enterprise enterprise;
    Network network;
    EcoSystem system;
    ArrayList<AdoptionWorkRequest> list=new ArrayList<AdoptionWorkRequest>();
    
    public ReciveAdoptionWorkRequest(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userAccount=userAccount;
        this.organization=organization;
        this.enterprise=enterprise;
        this.network=network;
        this.system=system;
        
        populateWorkRequest();
    }


        private void populateWorkRequest() {
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        
        model.setRowCount(0);
        
        for (WorkRequest wr: organization.getAdoptionWorkQueue().getAdoptionWorkRequestList()){
            AdoptionWorkRequest awr = (AdoptionWorkRequest)wr;
            Object[] row = new Object[3];
            row[0] = awr;
            row[1] = awr.getMessage();
            row[2] = awr.getStatus();
            model.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtFeedback = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtBreed = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSpecie = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtZip = new javax.swing.JTextField();
        txtFund = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtHome = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        txtAllergy = new javax.swing.JTextField();
        jCheckBox3 = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Manage Adoption");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Message", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 63, 901, 275));

        jButton1.setText("Detail");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 356, -1, -1));

        jLabel2.setText("Massage:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 384, -1, 20));
        add(txtFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 383, 150, -1));

        jButton2.setText("Send");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(823, 412, 73, -1));

        jLabel5.setText("Color:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 489, -1, 25));

        jLabel4.setText("Age:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 521, -1, 25));

        txtGender.setEditable(false);
        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });
        add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 459, 170, 25));

        txtAge.setEditable(false);
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 521, 170, 25));

        txtColor.setEditable(false);
        add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 489, 170, 25));

        txtBreed.setEditable(false);
        add(txtBreed, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 429, 170, 25));

        jLabel3.setText("Breed:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 429, -1, 25));

        jLabel6.setText("Gender:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 459, -1, 25));

        jLabel7.setText("Address:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 610, -1, 25));

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 610, 170, 25));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 671, -1, -1));

        jCheckBox1.setText("Valid Photo ID");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 399, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Checklist:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 360, 109, 21));

        jLabel9.setText("Specie:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 399, -1, 25));

        txtSpecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpecieActionPerformed(evt);
            }
        });
        add(txtSpecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 399, 170, 25));

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 13, -1, -1));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 14, 150, -1));

        jLabel11.setText("Name:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 556, -1, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 553, 170, -1));

        jLabel12.setText("Email:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 584, -1, -1));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 581, 170, -1));

        jLabel13.setText("ZipCode:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 645, -1, -1));
        add(txtZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 642, 170, -1));

        txtFund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFundActionPerformed(evt);
            }
        });
        add(txtFund, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 477, 128, -1));

        jLabel14.setText("$");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 480, -1, -1));

        jLabel15.setText("per Month");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 480, -1, -1));
        add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 507, 47, -1));

        jLabel16.setText("Hours per Day");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 510, -1, -1));
        add(txtHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 537, 142, -1));
        add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 413, 150, -1));

        jLabel10.setText("Status:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 416, -1, -1));

        jLabel17.setText("Name:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 17, -1, -1));

        jLabel18.setText("Fund:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 480, -1, -1));

        jLabel19.setText("Time:");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 510, -1, -1));

        jLabel20.setText("Home:");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 540, -1, -1));

        jCheckBox2.setText("Had Pet Before");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 424, -1, -1));

        jLabel21.setText("Allergy History:");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 569, -1, -1));
        add(txtAllergy, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 566, 136, -1));

        jCheckBox3.setText("Having pet Currently");
        add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 449, -1, -1));

        jButton4.setText("Submit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 671, -1, -1));

        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(836, 13, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable.getSelectedRow();
        AdoptionWorkRequest awr = (AdoptionWorkRequest)jTable.getValueAt(selectedRow, 0);
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null,"please select a row first!");
            return;
        }
        else{
            awr.setMessage(txtFeedback.getText());
            awr.setStatus(txtStatus.getText());            
            populateWorkRequest();
            txtFeedback.setText("");
            txtStatus.setText("");
        }
        JOptionPane.showMessageDialog(null, "Request Sent!");
        
        for(Organization o: enterprise.getOrganizationDirectory().getOrganizationList()){
            if(o instanceof InventoryOrganization){
             o.getAdoptionWorkQueue().getAdoptionWorkRequestList().add(awr);
            }
        }
        
        Animal an = awr.getAnimal();
        Customer adopter=awr.getAdopter();
        InspectionWorkRequest inswr = new InspectionWorkRequest();
        inswr.setSender(userAccount);
        inswr.setAnimal(an);
        inswr.setCustomer(adopter);
        inswr.setStatus("Generated");
        for(Organization o: enterprise.getOrganizationDirectory().getOrganizationList()){
            if(o instanceof InspectionOrganization){
                o.getInspectionWorkQueue().getWorkRequestList().add(inswr);
            }
        }
        if(inswr.getStatus().equalsIgnoreCase("Generated")){
            inswr.getCustomer().getUserAccount().getInspectionWorkQueue().getWorkRequestList().add(inswr);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable.getSelectedRow();
        
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null,"please select a row first!");
            return;
        }

        AdoptionWorkRequest awr = (AdoptionWorkRequest)jTable.getValueAt(selectedRow, 0);
        txtSpecie.setText(awr.getAnimal().getSpecies());
        txtBreed.setText(awr.getAnimal().getBreed());
        txtGender.setText(awr.getAnimal().getGender());
        txtColor.setText(awr.getAnimal().getColor());
        txtAge.setText(awr.getAnimal().getAge());
        txtName.setText(awr.getAdopter().getName());
        txtAddress.setText(awr.getAdopter().getAddress());
        txtEmail.setText(awr.getAdopter().getEmail());
        txtZip.setText(awr.getAdopter().getZipCode());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void txtSpecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpecieActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        /*int selectedRow = jTable.getSelectedRow();
        
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null,"please select a row first!");
            return;
        }*/
        jTable.removeAll();
        for(WorkRequest wr: organization.getAdoptionWorkQueue().getAdoptionWorkRequestList()){
            AdoptionWorkRequest awr = (AdoptionWorkRequest)wr;
            if(txtSearch.getText().equals(awr.getAdopter().getName())){
                DefaultTableModel dtm = (DefaultTableModel)jTable.getModel();
                dtm.setRowCount(0);
                Object[] row = new Object[3];
                row[0] = awr;
                row[1] = awr.getMessage();
                row[2] = awr.getStatus();
                dtm.addRow(row);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void txtFundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFundActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null,"please select a row first!");
            return;
        }
        AdoptionWorkRequest awr = (AdoptionWorkRequest)jTable.getValueAt(selectedRow, 0);
        if(jCheckBox1.isSelected()){
            awr.setValidId(Boolean.TRUE);
        }
        if(jCheckBox2.isSelected()){
            awr.setHadPet(Boolean.TRUE);
        }
        if(jCheckBox3.isSelected()){
            awr.setHavingPet(Boolean.TRUE);
        }
        awr.setFund(txtFund.getText());
        awr.setTime(txtTime.getText());
        awr.setHome(txtHome.getText());
        awr.setAllergy(txtAllergy.getText());
        txtFund.setText("");
        txtTime.setText("");
        txtHome.setText("");
        txtAllergy.setText("");
        JOptionPane.showMessageDialog(null, "Submit!");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        populateWorkRequest();
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAllergy;
    private javax.swing.JTextField txtBreed;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFeedback;
    private javax.swing.JTextField txtFund;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtHome;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSpecie;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTime;
    private javax.swing.JTextField txtZip;
    // End of variables declaration//GEN-END:variables


    
}
