/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CertificationManager;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.InventoryOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LostAnimalWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emmet Zhao
 */
public class ReciveLostAnimalWorkRequest extends javax.swing.JPanel {

    /**
     * Creates new form ManageLostPet
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    Organization organization;
    Enterprise enterprise;
    Network network;
    EcoSystem system;
    public ReciveLostAnimalWorkRequest(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userAccount=userAccount;
        this.organization=organization;
        this.enterprise=enterprise;
        this.network=network;
        this.system=system;
        
        populateWorkRequest();
    }

    private void populateWorkRequest() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        model.setRowCount(0);
        
        for (WorkRequest wr: organization.getLostAnimalWorkQueue().getWorkRequestList()){
            LostAnimalWorkRequest lawr = (LostAnimalWorkRequest)wr;
            Object[] row = new Object[3];
            row[0] = wr;
            row[1] = wr.getMessage();
            row[2] = wr.getStatus();
            
            
            
            
            
            model.addRow(row);
        }
    }
    
    public void populateimage(String url, JLabel lbl) {

            ImageIcon imageIcon = new ImageIcon(url);
            Image image = imageIcon.getImage();
            Image smallImage = image.getScaledInstance(200, 200, Image.SCALE_FAST);
            ImageIcon smallIcon = new ImageIcon(smallImage);
            lbl.setIcon(smallIcon);
            
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtBreed = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSpecie = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtZip = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFeedback = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        txtStatus = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        systemPhoto = new javax.swing.JLabel();
        customerPhoto = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Manage Lost Pet");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Massage", "Status"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 930, 254));

        jButton2.setText("Detail");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 80, 40));

        jLabel5.setText("Color:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, 25));

        jLabel4.setText("Age:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, 25));

        txtGender.setEditable(false);
        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });
        add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 170, 25));

        txtAge.setEditable(false);
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 170, 25));

        txtColor.setEditable(false);
        add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 170, 25));

        txtBreed.setEditable(false);
        add(txtBreed, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 170, 25));

        jLabel3.setText("Breed:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, 25));

        jLabel6.setText("Gender:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, 25));

        jLabel9.setText("Species:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, 25));

        txtSpecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpecieActionPerformed(evt);
            }
        });
        add(txtSpecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 168, 25));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, -1, -1));

        jCheckBox1.setText("Valid Photo ID");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, -1));

        jCheckBox2.setText("Receipt of Purchase");
        add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 150, -1));

        jCheckBox3.setText("Vaccine History");
        add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 140, -1));

        jLabel11.setText("Name:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, -1, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, 170, -1));

        jLabel12.setText("Email:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, -1, -1));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 600, 170, -1));

        jLabel13.setText("ZipCode:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, -1, -1));
        add(txtZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 170, -1));

        jLabel7.setText("Address:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, 25));

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 170, 25));

        jLabel2.setText("Massage:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 580, -1, 20));

        txtFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFeedbackActionPerformed(evt);
            }
        });
        add(txtFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 580, 150, -1));

        jButton3.setText("Send");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 670, -1, -1));
        add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 620, 150, -1));

        jLabel10.setText("Status:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 620, 50, 20));

        jButton4.setText("Submit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 680, -1, -1));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 120, -1));

        jLabel17.setText("Name:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        jButton6.setText("Refresh");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("System photo");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, 140, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Checklist:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 109, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Customer photo");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 140, 40));

        systemPhoto.setText("    system photo");
        add(systemPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 150, 160));

        customerPhoto.setText("    customer photo");
        add(customerPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 150, 160));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null,"please select a row first!");
            return;
        }
        
        LostAnimalWorkRequest lawr = (LostAnimalWorkRequest)jTable1.getValueAt(selectedRow, 0);
        txtSpecie.setText(lawr.getAnimal().getSpecies());             
        txtBreed.setText(lawr.getAnimal().getBreed());
        txtGender.setText(lawr.getAnimal().getGender());
        txtColor.setText(lawr.getAnimal().getColor());
        txtAge.setText(lawr.getAnimal().getAge());
        txtName.setText(lawr.getLostCustomer().getName());
        txtAddress.setText(lawr.getLostCustomer().getAddress());
        txtEmail.setText(lawr.getLostCustomer().getEmail());
        txtZip.setText(lawr.getLostCustomer().getZipCode());
        //customerPhoto.setIcon(lawr.getIcon());
        //systemPhoto.setIcon(lawr.getAnimal().getIcon());
        populateimage(lawr.getPicturepath(), customerPhoto);
        populateimage(lawr.getAnimal().getPicturepath(), systemPhoto);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtSpecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpecieActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
            LostAnimalWorkRequest lawr = (LostAnimalWorkRequest)jTable1.getValueAt(selectedRow, 0);

        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null,"please select a row first!");
            return;
        }
        else{
            lawr.setMessage(txtFeedback.getText());
            lawr.setStatus(txtStatus.getText());
            populateWorkRequest();
            txtFeedback.setText("");
            txtStatus.setText("");
        }
        JOptionPane.showMessageDialog(null, "Request Sent!");
        
        for(Organization o: enterprise.getOrganizationDirectory().getOrganizationList()){
            if(o instanceof InventoryOrganization){
             o.getLostAnimalWorkQueue().getWorkRequestList().add(lawr);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFeedbackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFeedbackActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null,"please select a row first!");
            return;
        }
            LostAnimalWorkRequest lawr = (LostAnimalWorkRequest)jTable1.getValueAt(selectedRow, 0);        if(jCheckBox1.isSelected()){
            lawr.setValidId(Boolean.TRUE);
        }
        if(jCheckBox2.isSelected()){
            lawr.setReceipt(Boolean.TRUE);
        }
        if(jCheckBox3.isSelected()){
            lawr.setVaccineHistory(Boolean.TRUE);
        }
        JOptionPane.showMessageDialog(null, "Submit!");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        /*int selectedRow = jTable.getSelectedRow();

        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null,"please select a row first!");
            return;
        }*/
        jTable1.removeAll();
        for(WorkRequest wr: organization.getLostAnimalWorkQueue().getWorkRequestList()){
            LostAnimalWorkRequest awr = (LostAnimalWorkRequest)wr;
            if(txtSearch.getText().equals(awr.getLostCustomer().getName())){
                DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
                dtm.setRowCount(0);
                Object[] row = new Object[3];
                row[0] = awr;
                row[1] = awr.getMessage();
                row[2] = awr.getStatus();
                dtm.addRow(row);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        populateWorkRequest();
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel customerPhoto;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel systemPhoto;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBreed;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFeedback;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSpecie;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtZip;
    // End of variables declaration//GEN-END:variables
}
