/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CustomerRole;

import Business.Animal.Animal;
import Business.Animal.AnimalDirectory;
import Business.EcoSystem;
import Business.Enterprise.AnimalShelterEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Youming Zheng
 */
public class SearchForAdoption extends javax.swing.JPanel {

    /**
     * Creates new form SearchForAdoption
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    Enterprise enterprise;
    Network network;
    EcoSystem system;
    ArrayList<Animal> lalala=new ArrayList<Animal>();
    Animal ann;
    AnimalShelterEnterprise asee;
    
    SearchForAdoption(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, Network network, EcoSystem system) {
       initComponents();
       this.userProcessContainer=userProcessContainer;
       this.userAccount=userAccount;
       this.enterprise=enterprise;
       this.network=network;
       this.system=system;
       
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        model.setRowCount(0);
        
      
            for (Animal animal : lalala){
            Object[] row = new Object[5];
            row[0] = animal;
            row[1] = animal.getSpecies();
            row[2]=animal.getBreed();
            row[3]=animal.getColor();
            row[4]=animal.getAge();

           
            
            model.addRow(row);
            }
        
    }
    
    public void populateimage(String url, JLabel lbl) {

            ImageIcon imageIcon = new ImageIcon(url);
            Image image = imageIcon.getImage();
            Image smallImage = image.getScaledInstance(200, 200, Image.SCALE_FAST);
            ImageIcon smallIcon = new ImageIcon(smallImage);
            lbl.setIcon(smallIcon);
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSSpecies = new javax.swing.JTextField();
        txtSBreed = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtBreed = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSpecies = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlPhoto = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtZipCode = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Species:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 55, -1, -1));

        jLabel2.setText("Breed:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 55, -1, -1));
        add(txtSSpecies, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 52, 157, -1));
        add(txtSBreed, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 52, 157, -1));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 51, -1, -1));

        jButton2.setText("See Details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 350, -1, -1));

        txtBreed.setEditable(false);
        add(txtBreed, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 477, 170, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 672, -1, -1));

        jLabel5.setText("Species:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 440, -1, -1));

        jLabel3.setText("Breed:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 480, -1, -1));

        txtSpecies.setEditable(false);
        add(txtSpecies, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 437, 170, -1));

        jLabel4.setText("Gender:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 515, -1, -1));

        jLabel6.setText("Color:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 555, -1, -1));

        jlPhoto.setText("           photo here");
        add(jlPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 438, 189, 165));

        jLabel7.setText("Age:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, -1, -1));

        txtGender.setEditable(false);
        add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 512, 170, -1));

        txtAge.setEditable(false);
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, 170, -1));

        txtColor.setEditable(false);
        add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 552, 170, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Animal Information:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 382, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Shelter Information:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 382, -1, -1));

        jLabel10.setText("Address:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 442, -1, -1));

        jLabel11.setText("Zip Code:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, -1, -1));

        txtAddress.setEditable(false);
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 439, 170, -1));

        txtZipCode.setEditable(false);
        add(txtZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 170, -1));

        jButton3.setText("Apply For Adoption");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 672, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Species", "Breed", "Color", "Age"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 88, 854, 255));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel12.setText("Search Adoption");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        lalala.clear();
        
        for(Enterprise en:network.getEnterpriseDirectory().getEnterpriseList()){
            if(en instanceof AnimalShelterEnterprise){
                for(Animal animal:en.getAnimalDirectory().getAnimalDirectory()){
                    if((animal.getSpecies().equalsIgnoreCase(txtSSpecies.getText())) && (animal.getBreed().equalsIgnoreCase(txtSBreed.getText()))  ||  ((txtSSpecies.getText().equals("")) && (txtSBreed.getText().equals("")))){
                       if(animal.isStatus()) 
                           lalala.add(animal);
                    }
                }
            }
        }
        
        populateTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //Animal an=new Animal();
        //AnimalShelterEnterprise ase=new ;
        
        int selectedRow=jTable1.getSelectedRow();
        
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please Select a Row First!","Warining",JOptionPane.WARNING_MESSAGE);
            return;
        }
        Animal an=(Animal)jTable1.getValueAt(selectedRow, 0);
        
        txtSpecies.setText(an.getSpecies());
        txtBreed.setText(an.getBreed());
        txtGender.setText(an.getGender());
        txtColor.setText(an.getColor());
        txtAge.setText(an.getAge());
        //jlPhoto.setIcon(an.getIcon());
        populateimage(an.getPicturepath(), jlPhoto);
        
        for(Enterprise ase:network.getEnterpriseDirectory().getEnterpriseList()){
            if(ase instanceof AnimalShelterEnterprise){
                for(Animal ani:ase.getAnimalDirectory().getAnimalDirectory()){
                    if(ani == an){
                        txtAddress.setText(ase.getAddress());
                        txtZipCode.setText(ase.getZipCode());
                        asee=(AnimalShelterEnterprise) ase;
                        break;
                    }
                }
            }
        }
        
        ann=an;
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        AdoptionConfirmation adcm = new AdoptionConfirmation(userProcessContainer, userAccount, ann, asee, enterprise, network, system);
        userProcessContainer.add("AdoptionConfirmation", adcm);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlPhoto;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBreed;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtSBreed;
    private javax.swing.JTextField txtSSpecies;
    private javax.swing.JTextField txtSpecies;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables
}
