/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.InventoryManager;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LostAnimalWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emmet Zhao
 */
public class ReceiveLostAnimalWorkRequest extends javax.swing.JPanel {

    /**
     * Creates new form ReceiveLostAnimalWorkRequest
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    Organization organization;
    Enterprise enterprise;
    Network network;
    EcoSystem system;
    public ReceiveLostAnimalWorkRequest(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userAccount=userAccount;
        this.organization=organization;
        this.enterprise=enterprise;
        this.network=network;
        this.system=system;
        
        populateWorkRequest();
    }

    private void populateWorkRequest() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        model.setRowCount(0);
        
        for (WorkRequest wr: organization.getLostAnimalWorkQueue().getWorkRequestList()){
            LostAnimalWorkRequest lawr = (LostAnimalWorkRequest)wr;
            Object[] row = new Object[3];
            row[0] = lawr;
            row[1] = lawr.getMessage();
            row[2] = lawr.getStatus();
            
            
            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtBreed = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSpecie = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtZip = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtSearch = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Massage", "Status"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 51, 1033, 254));

        jButton2.setText("Detail");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 312, -1, -1));

        jLabel5.setText("Color:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 477, -1, 25));

        jLabel4.setText("Age:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 507, -1, 25));

        txtGender.setEditable(false);
        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });
        add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 447, 170, 25));

        txtAge.setEditable(false);
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 507, 170, 25));

        txtColor.setEditable(false);
        add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 477, 170, 25));

        txtBreed.setEditable(false);
        add(txtBreed, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 417, 170, 25));

        jLabel3.setText("Breed:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 417, -1, 25));

        jLabel6.setText("Gender:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 447, -1, 25));

        jLabel9.setText("Species:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 387, -1, 25));

        txtSpecie.setEditable(false);
        txtSpecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpecieActionPerformed(evt);
            }
        });
        add(txtSpecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 387, 168, 25));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 550, -1, -1));

        jLabel11.setText("Name:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 417, -1, -1));

        txtName.setEditable(false);
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 417, 170, -1));

        jLabel12.setText("Email:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 447, -1, -1));

        txtEmail.setEditable(false);
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 447, 170, -1));

        jLabel13.setText("ZipCode:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 477, -1, -1));

        txtZip.setEditable(false);
        add(txtZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 477, 170, -1));

        jLabel7.setText("Address:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 387, -1, 25));

        txtAddress.setEditable(false);
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 387, 170, 25));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 13, 120, -1));

        jLabel17.setText("Name:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 13, -1, -1));

        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(878, 13, -1, -1));

        jButton6.setText("Refresh");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(968, 13, -1, -1));

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 312, -1, -1));

        jLabel2.setText("Animal:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 364, -1, -1));

        jLabel8.setText("Customer");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 364, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel10.setText("Lost Animal Work Request");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();

        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null,"please select a row first!");
            return;
        }

        LostAnimalWorkRequest lawr = (LostAnimalWorkRequest)jTable1.getValueAt(selectedRow, 0);
        txtSpecie.setText(lawr.getAnimal().getSpecies());
        txtBreed.setText(lawr.getAnimal().getBreed());
        txtGender.setText(lawr.getAnimal().getGender());
        txtColor.setText(lawr.getAnimal().getColor());
        txtAge.setText(lawr.getAnimal().getAge());
        txtName.setText(lawr.getLostCustomer().getName());
        txtAddress.setText(lawr.getLostCustomer().getAddress());
        txtEmail.setText(lawr.getLostCustomer().getEmail());
        txtZip.setText(lawr.getLostCustomer().getZipCode());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtSpecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpecieActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        /*int selectedRow = jTable.getSelectedRow();

        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null,"please select a row first!");
            return;
        }*/
        jTable1.removeAll();
        for(WorkRequest wr: organization.getLostAnimalWorkQueue().getWorkRequestList()){
            LostAnimalWorkRequest awr = (LostAnimalWorkRequest)wr;
            if(txtSearch.getText().equals(awr.getLostCustomer().getName())){
                DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
                Object[] row = new Object[3];
                row[0] = awr;
                row[1] = awr.getMessage();
                row[2] = awr.getStatus();
                dtm.addRow(row);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        populateWorkRequest();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();

        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null,"please select a row first!");
            return;
        }

        LostAnimalWorkRequest lawr = (LostAnimalWorkRequest)jTable1.getValueAt(selectedRow, 0);
        organization.getAdoptionWorkQueue().getAdoptionWorkRequestList().remove(lawr);
        
        populateWorkRequest();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBreed;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSpecie;
    private javax.swing.JTextField txtZip;
    // End of variables declaration//GEN-END:variables
}
